version: "3.9"

services:
  lab1:
    build: ./coupon_glitch
    ports:
      - "8001:80"

  lab3:
    build: ./file_upload
    ports:
      - "8002:80"
  lab4:
    build: ./user_role_modified
    ports:
      - "8003:80"
  lab5:
    build: ./xss_lab
    ports:
      - "8004:80"
  lab6:
    build: ./xss_level_2
    ports:
      - "8005:80"
  lab7:
    build: ./Infinite_Money_Glitch
    ports:
      - "8006:80"
  lab8:
    build: ./Unprotected_admin_functionality
    ports:
      - "8007:80"
  lab9:
    build: ./bank_lab
    ports:
      - "8008:80"
  lab10:
    build: ./xss_mullti_params
    ports:
      - "8009:80"
  lab11:
    build: ./broken_access_controll_by_cookiees
    ports:
      - "8010:80"