version: "3.9"

services:
  lab1:
    build: ./coupon_glitch
    ports:
      - "8001:80"

  lab3:
    build: ./file_upload
    ports:
      - "8002:80"
  lab4:
    build: ./user_role_modified
    ports:
      - "8003:80"
  lab5:
    build: ./xss_lab
    ports:
      - "8004:80"
